# Generated by Django 6.0.3 on 2026-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='save_by',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(choices=[('0-15', '0-15'), ('15-25', '15-25'), ('25-40', '25-40'), ('40+', '40+')], max_length=10),
        ),
    ]
